version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'

  auth:
    build: ./auth-service
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/authdb
      - JWT_SECRET=supersecretjwt

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - auth
